name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest  # 使用Windows操作系统

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: 1.8  # 在Windows上使用Java 8

    - name: Set up Maven
      run: |
        wget -q "https://archive.apache.org/dist/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.zip"
        Expand-Archive -Path apache-maven-3.8.4-bin.zip -DestinationPath C:\maven
        echo "export MAVEN_HOME=C:\maven\apache-maven-3.8.4" | Out-File -Append $PROFILE
        echo "export PATH=$PATH:$MAVEN_HOME\bin" | Out-File -Append $PROFILE
        RefreshEnv
      shell: PowerShell

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests
      run: mvn test

    # 这里可以添加更多的步骤，比如部署到服务器或发布到Maven仓库
