name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 20
      run: |
        wget https://example.com/path/to/your/custom/jdk20.tar.gz
        tar xzf jdk20.tar.gz -C /opt
        echo "export JAVA_HOME=/opt/jdk20" >> $GITHUB_ENV
        echo "export PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV
        java -version
      shell: bash

    - name: Set up Maven
      run: |
        wget -q "https://archive.apache.org/dist/maven/maven-3/3.9.4/binaries/apache-maven-3.9.4-bin.zip"
        unzip -q apache-maven-3.9.4-bin.zip -d /opt
        echo "export MAVEN_HOME=/opt/apache-maven-3.9.4" >> $GITHUB_ENV
        echo "export PATH=$MAVEN_HOME/bin:$PATH" >> $GITHUB_ENV
        mvn -v
      shell: bash

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests
      run: mvn test
